import os

RABBITMQ_USERNAME = os.environ["RABBITMQ_USERNAME"]
RABBITMQ_HOST = os.environ["RABBITMQ_HOST"]
RABBITMQ_PASSWORD = os.environ["RABBITMQ_PASSWORD"]
RABBITMQ_PORT = os.environ["RABBITMQ_PORT"]
RABBITMQ_BROKER = f"pyamqp://{RABBITMQ_USERNAME}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:{RABBITMQ_PORT}//"
