version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass guest

  worker: 
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=guest
      - REDIS_DB=0
    volumes:
      - .:/code
    depends_on:
      - redis
    command: celery -A cbf.worker worker --loglevel=INFO
