DEFAULT:
  QTD_CONSUMERS: 1
  RABBITMQ:
    HOST: "localhost"
    PORT: 5672
    VIRTUAL_HOST: "/"
    USER: "guest"
    PASSWORD: "guest"

DEV:
  DEMO:
    serie: "A"
    ano: 2023
    inicio: 1
    fim: 100
  RABBITMQ:
    HOST: "172.17.0.5"
    PORT: 5672
    VIRTUAL_HOST: "/"
    USER: "guest"
    PASSWORD: "guest"
