DEFAULT:
  QTD_CONSUMERS: 1
  RABBITMQ:
    HOST: "localhost"
    PORT: 5672
    VIRTUAL_HOST: "/"
    USER: "guest"
    PASSWORD: "guest"

DEV:
  RABBITMQ:
    HOST: "172.17.0.5"
    PORT: 5672
    VIRTUAL_HOST: "/"
    USER: "guest"
    PASSWORD: "guest"
